# Docker
# Build and push an image to Azure Container Registry

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - order-service/**

resources:
- repo: self

variables:
  # Container registry service connection
  dockerRegistryServiceConnection: 'b3526c77-a859-44cf-a612-b0f0397e14c9'

  # Image details
  imageRepository: 'order-service'
  containerRegistry: 'acrdocker.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/order-service/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage

  jobs:
  - job: Build
    displayName: Build

    pool:
      vmImage: $(vmImageName)

    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest